version: 2.1

jobs:
  download:
    docker:
      - image: cimg/base:stable
    steps:
      - run: wget http://speedtest.tele2.net/1GB.zip -O test.bin

workflows:
  download-workflow:
    jobs:
      - download